rvm: 1.8.7
notifications:
    email: false
env:
    - PUPPET_VERSION=3.8.2
    - PUPPET_VERSION=4.2.1
    - PUPPET_VERSION=2.6.18
    - PUPPET_VERSION=2.7.26
script:
    #- puppet-lint --no-80chars-check .
    - gem list
    - puppet parser validate .
